server:
  port: 8080
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/realestate?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: root123

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

jwt:
  secret-key: real_estate.find-my-perfect-room.secret-key
  token:
    expired-time-ms: 2592000000